sacatuturno/sacatuturno/urls.py
#from sacatuturno.sitio.views import home
from django.contrib import admin
from django.urls import path, include

from sitio import views



urlpatterns = [
    path('', include(('sitio.url'))),
    path('admin/', admin.site.urls)
]

 

sacatuturno/sitio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import DateTimeField
import datetime, time
from sitio import myFields

# Create your models here.

tipo_user = [
    ('cliente', 'CLIENTE'),
    ('profesional', 'PROFESIONAL')
]


ciudades = [
    ('Rafaela', 'Rafaela'),
    ('Santa Fe', 'Santa Fe'),
    ('Rosario', 'Rosario')
]


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    activation_key = models.CharField(max_length=255, blank=True)
    key_expires = models.DateTimeField(default=datetime.date.today())
    tipo = models.CharField(max_length= 16, choices=tipo_user, verbose_name= 'Tipo usuario', null = True, default = 'cliente' )

    @property 
    def traerServicio(self):
        return ServicioPrestado.objects.filter(propietario__id = self.id)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural=u'Perfiles de Usuario'




#categoria principal -> ej medicina, cuidado persona, etc.
class Categoria(models.Model):
    nombre = models.CharField(max_length=255, blank = False)
    
    @property 
    def traerSubcategorias(self):
        return SubCategoria.objects.filter(categoria__id = self.id)
        
    def __str__(self):
        return self.nombre



class SubCategoria(models.Model):
    nombre = models.CharField(max_length=255, blank = False)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre


class Days(models.Model):
    day = models.CharField(max_length=10)
    
    def __str__(self):
        return self.day

class ServicioPrestado(models.Model):
    nombre = models.CharField(max_length=50, blank = False)       # NO LLEVA NOMBRE EL SERVICIO PRESTADO
    descripcion = models.TextField(max_length=150, blank = False)
    propietario = models.ForeignKey(User, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, blank = True, null= True)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE, blank = True, null= True)
    diasAtencion = models.ManyToManyField(Days)
    duracionTurno = models.IntegerField(default = 30, null= False, blank = False)
    ciudad = models.CharField(max_length= 20, choices = ciudades, verbose_name='Ciudad', blank = True, null= True, default = 'Rafaela')
    inicioJornada = models.TimeField( auto_now=False, auto_now_add=False, verbose_name="Inicio de Jornada",blank=True, null=False, default='08:00:00')
    finJornada = models.TimeField( auto_now=False, auto_now_add=False, verbose_name="Fin de Jornada",blank=True, null=False, default='17:00:00')

    @property 
    def listaHorarios(self):
        horarios=[]
        inicio = self.inicioJornada
        #import ipdb; ipdb.set_trace();
        horarios.append(inicio)       
        while inicio <= self.finJornada:
            
            fecha_aux= datetime.datetime(2021,1,1,inicio.hour,inicio.minute,0)
            fecha_aux = fecha_aux + datetime.timedelta(minutes= self.duracionTurno)
            inicio = datetime.time(fecha_aux.hour,fecha_aux.minute)
            horarios.append(inicio)

        #import ipdb; ipdb.set_trace();
        return horarios

    def __str__(self):
        return self.nombre



class Turno(models.Model):
    servicio = models.ForeignKey(ServicioPrestado, on_delete=models.CASCADE)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    fecha_inicio = models.DateTimeField(verbose_name='Fecha inicio', default=datetime.datetime.today())
    horario = models.TimeField( auto_now=False, auto_now_add=False, verbose_name="Horario",blank=True, null=False, default='08:00:00')
    fecha_fin = models.DateTimeField(verbose_name='Fecha Fin',blank=True, null=True, default=datetime.datetime.today())
    confirmado = models.BooleanField( default=False)
    cliente_aux = models.TextField(max_length=50, blank = True, null=True)
    

sacatuturno/templates/agenda.html
{% extends "base.html" %}

{%block content %}

    {% for message in messages%}
        <h4 style = "margin: 0 auto; text-align: center; color: green">{{message}}</h2>
    {% endfor %}
    
    <h6 class="centeralign colorcito negrita tituloTurno " style="font-size: 70px !important;">{{servicio.nombre}}</h6>
    <br>
    
    <h4>Sacar Turno Manual</h4>
    <a class="btn btn-secondary" href="{% url 'pedir_turno' servicio.id user.id %}">Turno</a>
    <!-- <button id= 'botoncito' ></button> -->

    <div class="row" style="padding-bottom:40px;">
        <div class="col-lg-1 col-md-1"></div>
        <div class="col-lg-7 col-md-10">
            <div id='calendar'></div>
        </div>
        <div class="col-lg-3 col-md-2">
            <h3>Turnos Pendientes:</h3><br>             
            {% for t in turnos_sin_confirmar %}
                           
                <div class="card" style="width: 400px;">
                    <div class="card-body">
                        <h4 class="card-title letracaja colorcito text-uppercase">{{t.cliente.first_name}} {{t.cliente.last_name}}</h4>
                        <h6 class="card-subtitle letracaja mb-2 text-muted"> {{t.fecha_inicio }}</h6>
                        <button class="rightalign colorcito btn btn-secondary"> <a href="{% url 'cambiar_estado_turno' t.servicio.id t.id 1 %}" class="card-link luisito">Aceptar</a> </button>
                        <button class="rightalign colorcito btn btn-secondary"> <a href="{% url 'cambiar_estado_turno' t.servicio.id t.id 0 %}" class="card-link luisito">Rechazar</a> </button>   
                    </div>
                </div>
            {% empty %}
            <h4>No posee turnos pendientes</h4>
            {% endfor %}
        </div>
        <div class="col-lg-1 col-md-1"></div>
    </div>
    


    <div style="display: none" id="jsonData" data-json="{{ turnos }}"></div>

    <script>        
        document.addEventListener('DOMContentLoaded', function() {
            
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                locale : "es",
                initialView: 'timeGridWeek',
                slotMinTime: "07:00:00",
                slotMaxTime: "21:00:00",
                displayEventTime : false, 

                headerToolbar: {               
                },
            });
            var data = JSON.parse(document.querySelector("#jsonData").getAttribute('data-json'));     
            //console.log(data);
            for (let index = 0; index < data.length; index++) {
                calendar.addEvent({
                    title: data[index].cliente,
                    start: data[index].fecha_inicio,
                    end: data[index].fecha_fin,
                    allDay: false,
                    });  
            }
        
            calendar.render();
        });


    </script>

    <style>
        #calendar {
            max-width: 1000px;
            margin: 0 auto;
        }
        
    </style>
{% endblock %}    

sacatuturno/templates/base.html
{% include 'header.html' %}

<body>
    {% block content %}

    {% endblock %}
</body>

{% comment %} {% include 'footer.html' %} {% endcomment %}

sacatuturno/templates/categorias.html
{% include "header.html" %}

{%block content %}   
    


<div class="row margenizqconinferior superior " style="margin-bottom:10px;">
    <form method="GET" style="padding-left: 0px;">
        {%csrf_token%}
        <div>
            <input class="anchocien" type="text" name="buscar_servicio" id="" value="{{request.GET.buscar_servicio}}">
            <button class="btn btn-secondary btncategoria" type="submit">Buscar</button>
        </div> 
    </form>

</div>


<div class="row margenizqconinferior " style="margin-bottom:10px;">
    <div class="container" style="padding-left: 0px;">
        <div class="dropdown dropend">
            <button class="btn btn-secondary dropdown-toggle anchocien" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if subcategoria %}
                     {{ subcategoria.nombre}}
                {%else%}
                    Categorias
                {%endif%}
            </button>
            <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
                
                {%for categoria in categorias %}
                <div class="dropdown dropend">                   
                    <a class="dropdown-item dropdown-toggle" href="#" id="dropdown-layouts" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{categoria.nombre}}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown-layouts">
                        {% for subcategoria in categoria.traerSubcategorias.all %}
                            
                            <a class="dropdown-item" id = "item_subcategoria" href="{% url 'categorias_filtro' subcategoria.id%}">{{subcategoria.nombre}}</a>
                        {% endfor %}                       
                    </div>
                </div>
                {%endfor%}                
            </div>
        </div>
    </div>

</div>

<div class="row margenizqconinferior anchocien">
    <select name="elegir_ciudad" id = "elegir_ciudad" onchange="myFunction()">
        <option value="">
            {% if request.GET.elegir_ciudad %}
                {{request.GET.elegir_ciudad}}
            {% else %}
                Seleccione una ciudad
            {% endif %}
        </option>
        <option value="Rafaela">Rafaela</option>
        <option value="Santa Fe">Santa Fe</option>
        <option value="Rosario">Rosario</option>
    </select>

</div>

    <div class="card-group border border-black margenizqconinferior">  
            {%for item in servicios %}
            <div class="card">     
                <div class="card-body text-center">
                    <div class="card-title letracaja colorcito text-uppercase"><p>{{item.nombre}} </p> </div>
                    <h6 class="card-subtitle letracaja mb-2 text-muted">{{item.propietario.first_name}} {{item.propietario.last_name}}</h6>
                    <h6 class="card-subtitle letracaja mb-2 text-muted">{{item.categoria}}</h6>
                    <div class="panel-text"><p>{{item.descripcion}}</p></div>
                    <div class="panel-foocter textosacarturno"><a id="id_sacarTurno" class="btn btn-primary stretched-link textosacarturno " href="{% url 'pedir_turno' item.id item.propietario.id %}">Sacar turno</a></div>
                </div>
            </div>
             
            {%endfor%}  
    </div>


    <script>

    var items = document.querySelectorAll('#item_subcategoria');
    console.log(items);
    
    function redirigirCategoria(){
        var ciudad = document.getElementById("elegir_ciudad").value;
        var subcategoria = document.getElementById("dropdownMenuButton").innerText;
        if (ciudad = 'Seleccione una ciudad')
            url = 'http://sacatuturno.herokuapp.com/categorias/'+ subcategoria + '/';
        else 
            url = 'http://sacatuturno.herokuapp.com/categorias/'+ subcategoria + '/' + ciudad + '/';
        window.location.replace(url) 
    }
    
    for (var i = 0; i < items.length; i++) {
        items[i].addEventListener("click", redirigirCategoria);  
    }
    
    /*window.onload = function() {

    }*/

    function myFunction() {
        var ciudad = document.getElementById("elegir_ciudad").value;
        var subcategoria = document.getElementById("dropdownMenuButton").innerText
        if (subcategoria = 'Categorias')
            url = 'http://sacatuturno.herokuapp.com/categorias/'+ ciudad + '/';
        else 
            url = 'http://sacatuturno.herokuapp.com/categorias/'+ subcategoria + '/' + ciudad + '/';

        window.location.replace(url);
    }

    

        (function($bs) {
    const CLASS_NAME = 'has-child-dropdown-show';
    $bs.Dropdown.prototype.toggle = function(_orginal) {
        return function() {
            document.querySelectorAll('.' + CLASS_NAME).forEach(function(e) {
                e.classList.remove(CLASS_NAME);
            });
            let dd = this._element.closest('.dropdown').parentNode.closest('.dropdown');
            for (; dd && dd !== document; dd = dd.parentNode.closest('.dropdown')) {
                dd.classList.add(CLASS_NAME);
            }
            return _orginal.call(this);
        }
    }($bs.Dropdown.prototype.toggle);

    document.querySelectorAll('.dropdown').forEach(function(dd) {
        dd.addEventListener('hide.bs.dropdown', function(e) {
            if (this.classList.contains(CLASS_NAME)) {
                this.classList.remove(CLASS_NAME);
                e.preventDefault();
            }
            e.stopPropagation(); // do not need pop in multi level mode
        });
    });

    // for hover
    document.querySelectorAll('.dropdown-hover, .dropdown-hover-all .dropdown').forEach(function(dd) {
        dd.addEventListener('mouseenter', function(e) {
            let toggle = e.target.querySelector(':scope>[data-bs-toggle="dropdown"]');
            if (!toggle.classList.contains('show')) {
                $bs.Dropdown.getOrCreateInstance(toggle).toggle();
                dd.classList.add(CLASS_NAME);
                $bs.Dropdown.clearMenus();
            }
        });
        dd.addEventListener('mouseleave', function(e) {
            let toggle = e.target.querySelector(':scope>[data-bs-toggle="dropdown"]');
            if (toggle.classList.contains('show')) {
                $bs.Dropdown.getOrCreateInstance(toggle).toggle();
            }
        });
    });
})(bootstrap);
    </script>

{% endblock %}

sacatuturno/templates/footer.html
<footer class="bg-light text-center  mt-3">
    <!-- Grid container -->
    <div class="container p-4 pb-0" >
      <!-- Section: Social media -->
      <section class="mb-4 " >
        <!-- Facebook -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-linkedin"></i
        ></a>
        <!-- Github -->
        <a
          class="btn btn-link btn-floating btn-lg text-dark m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3 fondoheader  colorcito" >
      © 2021 Copyright:
      <a class="colorcito" href="https://mdbootstrap.com/">FORNASERO-CRAVERO SOLUCIONES PYTHONERAS</a>
    </div>
    <!-- Copyright -->
  </footer>

sacatuturno/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'sitio/styles.css' %}">
    <link rel="stylesheet" href="{% static 'fullcalendar/main.css' %}">
    <title></title>
</head>
<body>   
      <nav class="navbar navbar-expand-lg navbar-dark fondoheader">
        <div class="container">
            <a class="navbar-brand negrita" href="{% url 'home' %}"> Saca tu Turno </a>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    
                    {% if request.user.is_active %}
                      <!-- <li class="nav-item" style="margin-left: 500px;"><a class ="nav-link" href="{%url 'registrarservicio'%}">Ofrecer servicio</a></li> -->
                      <li class="nav-item estiloheader"><a class ="nav-link" href="{% url 'perfil' request.user.id %}">Perfil</a></li>
                      <li class="nav-item"><a class ="nav-link" href="{%url 'logout'%}">Cerrar Sesion</a></li>
                      
                    {% else %}
                      <li class="nav-item estiloheader" ><a class ="nav-link" href= "{%url 'login'%}">Ingresar</a></li>
                      <li class="nav-item" ><a class ="nav-link" href= "{%url 'crearcuenta'%}">Crear Cuenta</a></li>
                    {% endif %}
                    <li class="nav-item"><a class ="nav-link" href="http://sacatuturno.herokuapp.com/search/">Buscar</a></li>
                </ul>
            </div>
        </div>
       
    </nav>
    


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- <script src='lib/jquery-ui.custom-datepicker.js'></script> -->
    <script src="{% static 'fullcalendar/main.js' %}"></script>
    <script src="{% static 'fullcalendar/locales-all.js' %}"></script>
    <!-- <script src="{% static 'fullcalendar/locales/es.js' %}"></script> -->
</body>
</html>

sacatuturno/templates/home.html
{% extends "base.html" %}


    <div class="container-fluid text-center">
        {%block content %}
        <div class="container colorcito">
            <h1 class="estilohome centeralign">Bienvenido!</h1>          
        </div>
        
        
        <div class="container">
            <div class="row">
                <div class="col-3 border-0"></div>
                <div class="col-3">
                    <a href="{%url 'categorias'%}">
                        <div class="card" style="border-style: none!important;">
                            <img class="card-img-top" src="https://cdn-icons-png.flaticon.com/512/661/661512.png" alt="logo turno">
                            <div class="card-body colorcito letracaja centeralign negrita"> <a style="font-size: 25px;">SACAR UN TURNO</a>  </div>
                        </div>
                    </a>                    
                </div>
                <div class="col-3 border-0">
                    <a href="{%url 'registrarservicio'%} ">
                        <div class="card" style="border-style: none!important;">
                            <img class="card-img-top" src="https://cdn-icons-png.flaticon.com/512/686/686348.png" alt="Card image cap">
                            <div class="card-body colorcito letracaja centeralign negrita"> <a style="font-size: 25px;"> OFRECER SERVICIO </a></div>
                        </div>
                    </a>
                </div>
                <div class="col-3"></div>                
            </div>                      
        </div>   
        

            {% if estadoActivacion %}
                <div class="alert alert-secondary" role="alert">
                    {{estadoActivacion}}
                </div>
            
            {% endif %}
        {% endblock %}
    </div>

 

sacatuturno/templates/logout.html
{% include "base.html" %}

<h1 class="centeralign colorcito negrita tituloTurno">Gracias por utilizar el sitio</h1>

<script type="text/javascript">
    //Redireccionamiento tras 5 segundos
    setTimeout( function() { window.location.href = "{% url 'home' %}"; }, 2000 );
 </script>

sacatuturno/templates/paginaprivada.html
{% extends "base.html" %}

{%block content %}
    <h1>Pagina solo para usuarios logueados</h1>
    {% if request.user.is_active %}
        <h3>Gracias por loguearte {{request.user.username}}</h3>
    {% endif %}
{% endblock %}

sacatuturno/templates/registrarservicio.html
{% include "header.html" %}

<form method="post">
        {%csrf_token%}
             
        <section class="vh-100 gradient-custom">
        <div class="container py-3 h-80">
                <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-10 col-lg-8 col-xl-8">
                <div class="card bg-dark text-white cajaborde">
                <div class="card-body mt-3 text-center">

                        <div class="mb-md-5 mt-md-4 pb-2">
                                {%if servicio  %}
                                <h2 class="fw-bold mb-4 text-uppercase  titulocaja text-center colorcito">MODIFICAR SERVICIO </h2>
                                {% else %}
                                <h2 class="fw-bold mb-4 text-uppercase titulocaja text-center colorcito">CREAR SERVICIO </h2>
                                {%endif%}
                                <p class="text-white-50 mb-5 text-center">Complete los campos solicitados</p>
                                                        
                                
                                <div class="form-outline form-white mb-4 row" >
                                        <label class="form-label letracaja col-6 rightalign"  >Nombre del servicio: </label>
                                        <a class="col-6 anchocien" > 
                                        {{form.nombre}}
                                        </a>
                                </div>

                                <div class="form-outline form-white mb-4 mt-3 row">
                                        <label class="form-label letracaja col-6 rightalign">Descripcion del servicio:</label>
                                        <a class="col-6 anchocien"> 
                                        {{form.descripcion}}
                                        </a>
                                </div>
                                <div class="form-outline form-white mb-4 mt-5 row">
                                        <label class="form-label letracaja col-6 rightalign">Categoría:</label>
                                        <a class="col-6 anchocien">
                                                {%if servicio %}
                                                <select  name="categoria" onchange="mostrarSubcategorias()" id="id_categoria">
                                                        <option class="anchocien" value="{{servicio.categoria.id}}" selected="">{{servicio.categoria}}</option>
                                                        
                                                </select>                                                                                                     
                                                {% else %}
                                                        <div class="anchocien" > {{form.categoria}}  </div>
                                                {%endif%}                     
                                        </a>
                                </div>
                                <div class="form-outline form-white mb-4 row">
                                        <label class="form-label letracaja col-6 rightalign">Sub-Categoría:</label>
                                        <a class="col-6 anchocien">
                                                {%if servicio %}
                                                <select name="subcategoria" onchange="mostrarSubcategorias()" id="id_subcategoria">
                                                        <option value="{{servicio.subcategoria.id}}" selected="">{{servicio.subcategoria}}</option>
                                                
                                                </select>                                                                                                        
                                                {% else %}
                                                        <select class="anchocien" name="subcategoria" data-minimum-input-length="0" data-allow-clear="true" data-placeholder id="id_subcategoria"></select> 
                                                {%endif%} 
                                        </a>
                                </div> 
                                                               

                                <div class="form-outline form-white mb-4 row" >
                                        <label class="form-label letracaja col-6 rightalign"  >Duración del turno (minutos): </label>
                                        <a class="col-6 anchocien" > 
                                                {{form.duracionTurno}}
                                        </a>
                                </div>

                                <div class="form-outline form-white mb-4 row">
                                        <label class="form-label letracaja col-6 rightalign"  >Ciudad: </label>
                                        <a class="col-6 anchocien" > 
                                                {{form.ciudad}}
                                        </a>
                                </div>

                                <div class="form-outline form-white mb-4 row">
                                        <label class="form-label letracaja col-6 rightalign"  >Inicio de Jornada: </label>
                                        <a class="col-6 anchocien" > 
                                                {{form.inicioJornada}}
                                        </a>
                                </div>

                                <div class="form-outline form-white mb-4 row">
                                        <label class="form-label letracaja col-6 rightalign"  >Fin de Jornada: </label>
                                        <a class="col-6 anchocien" > 
                                                {{form.finJornada}}
                                        </a>
                                </div>

                                <div class="form-outline form-white row d-flex" style="height: 185px;">
                                        <label class="form-label letracaja col-6 rightalign" >Días disponible: </label>   
                                        {{form.diasAtencion}}
                                        
                                </div>
                                
                                {%if servicio %}
                                <button class="btn btn-outline-light btn-lg px-5 colorcito" type="submit">Guardar Cambios</button>  
                                {% else %}
                                <button class="btn btn-outline-light btn-lg px-5 colorcito" type="submit">Crear</button>  
                                {%endif%}
                                                                
                                
                                </div>
                        </div>
                        </div>
                        </div>
                </div>
        </div>
        </section>

            

</form>

{% for message in messages %}
    
    <div class="alert">
        <a class="close" href="#" data-dismiss="alert">×</a>
           {{ message }}
    </div>

{% endfor %}

<script>

        function mostrarSubcategorias(){
        var x = document.getElementById("id_categoria").value
        $.ajax({
                url: "../traerSubcategorias/" + x,
                type: 'GET',
                dataType: 'json',
                success: function(data){
                        var select = document.getElementById("id_subcategoria");
                        for (let i = select.options.length; i >= 0; i--) {
                                select.remove(i);
                        }

                        if (data.length != 0){
                                for (let i = 0; i < data.length; i++){
                                        var option = document.createElement('option');
                                        option.value = data[i].pk;
                                        option.text = data[i].fields.nombre;
                                        select.appendChild(option);
                                }
                        }
                        else{
                                var option = document.createElement('option');
                                option.text = "No existen subcategorias registradas";
                                option.disabled = true;
                                select.appendChild(option);
                        }
                        },
                error: function() {
                        var select = document.getElementById("id_subcategoria");
                        for (let i = select.options.length; i >= 0; i--) {
                                select.remove(i);
                        }
                        }
        });

        }

        const listaElem = document.querySelectorAll('#id_diasAtencion li');
        console.log(listaElem);
        for (let index = 0; index < listaElem.length; index++) {
                listaElem[index].classList.add('row');             
        }

        const imputs = document.querySelectorAll('#id_diasAtencion li input');
        console.log(listaElem);
        for (let index = 0; index < imputs.length; index++) {
                imputs[index].classList.remove('col-6');
                imputs[index].classList.add('col');             
        }

        const labels = document.querySelectorAll('#id_diasAtencion li label');
        console.log(listaElem);
        for (let index = 0; index < labels.length; index++) {
                 labels[index].classList.add('col');             
        }

</script>

sacatuturno/templates/subcategoria.html
{% extends "base.html" %}

{%block content %}
    <h1> Subcategoria </h1>
        <ul>
            {%for item in subcategoria %}
            <li><a href="{% url 'servicios' item.id %}">{{item.nombre}}</a></li>
            {%endfor%}  
        </ul>   
{% endblock %}